### ISSUE TITLE
Highlight issue of function names and local variables

### ISSUE THREAD

**Issue by yitzman** [FINNSEEFLY/Darcula-Theme-VS-2022#25] opened 2024-02-19 20:03 UTC
Hi, Thank you so much for this theme. I have been using it consistently for years. 
Since the latest VS update 17.9.0 there has been an issue with the highlighting of function names that were usually in yellow and are now purple.
![image](https://github.com/FINNSEEFLY/Darcula-Theme-VS-2022/assets/38329004/e80b605e-05d1-4d46-bfbe-ffc7f0604143)

Also, local variables were usually white and are now also purple.
![image](https://github.com/FINNSEEFLY/Darcula-Theme-VS-2022/assets/38329004/66a5366c-4442-44ea-8147-c2460161f313)

Thanks in advance, Yitzi

**Comment by FINNSEEFLY** [comment] 2024-02-20 21:09
Hi, thanks for the feedback and issue details! 
I've just published v1.1.5 and I hope the problem is fixed now.

**Closed by FINNSEEFLY** 2024-02-20 21:09 UTC
Labels: bug

**Comment by yitzman** [comment] 2024-02-20 21:54
Looks Great! Thanks for the quick fix!
